apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ts-react-client-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  # The hyphen here is the key. It starts a new item in the 'rules' list.
  - http:
      paths:
      # Rule for the API Gateway
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ts-api-gateway
            port:
              number: 8080
      # Rule for the frontend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ts-react-client-service
            port:
              number: 5173