apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ts-react-client-ingress-dev
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - dev.tinystepscdc.com
    secretName: dev-tinystepscdc-tls
  rules:
  - host: dev.tinystepscdc.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ts-api-gateway
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ts-react-client-service
            port:
              number: 80