name: Build, Push, and Deploy
env:
  SERVICE_NAME: ts-client
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.generate_tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate image tag
        id: generate_tag
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          echo "tag=${SHORT_SHA}-${TIMESTAMP}" >> $GITHUB_OUTPUT

      - name: Set up pack
        uses: buildpacks/github-actions/setup-pack@v5.6.0

      - name: Build and push image
        run: |
          IMAGE_NAME="${{ env.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}"
          IMAGE_TAG="${{ steps.generate_tag.outputs.tag }}"
          pack build "${IMAGE_NAME}" --builder paketobuildpacks/builder:base --publish --tag "${IMAGE_NAME}:${IMAGE_TAG}"

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure Kubernetes cluster connection
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes using Kustomize
        run: |
          IMAGE_TAG="${{ needs.build-and-push.outputs.tag }}"
          cd k8s

          kustomize edit set image subhankarm2312/ts-client:${IMAGE_TAG}

          kubectl apply -k .
